# Generated by Django 5.2.3 on 2025-06-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0002_singer_song_delete_sing'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='무제', max_length=100),
            preserve_default=False,
        ),
    ]
