# Generated by Django 5.2.3 on 2025-07-14 16:39

import sing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sing', '0004_tag_singer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sing.models.image_upload_path),
        ),
    ]
